### ISSUE TITLE
Why not use Grafana's own solution?

### ISSUE THREAD

**Issue by AndersBennedsgaard** [lunarway/grafana-sidecar#3]
Have you considered using Grafanas own solution to this problem? They use `quay.io/kiwigrid/k8s-sidecar` which enables you to create `ConfigMap`s with the dashboards in json format.

For example, adding the sidecar using their Helm chart at https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L636, enables you to add dashboards by adding a `grafana_dashboard=1` label to your `ConfigMap`. I believe it is possible to specify which folder to add the dashboard to, using the `k8s-sidecar-target-directory=/tmp/dashboards/folder` annotation, but I haven't tested this..

**Comment by Crevil** [comment]
I haven't seen that project but it sure looks identical in scope as this. And also better maintained from the looks of it.

This project is not a priority for us at the moment but it might just be that we would decide to shut it down completely in favor of the other 😄
